storage_path: postgres://saljaev:secret@localhost:5432/kosloeb?sslmode=disable
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  secret: secret
  token_ttl: 5m
  session_ttl: 1h
  token_length: 10
