storage_path: postgres://saljaev:secret@db:5432/kosloeb?sslmode=disable
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
secret: secret
token_ttl: 5m
session_ttl: 1h
#token_length: 10
